# Generated by Django 5.0.4 on 2024-04-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('date_of_burial', models.DateField()),
                ('obituary', models.TextField()),
                ('portrait_image', models.ImageField(upload_to='')),
                ('landscape_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Plot_Status',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
                ('color_hex', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('plot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plot_latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('plot_longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.person')),
                ('plot_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.plot_status')),
            ],
        ),
    ]
