# Generated by Django 5.0.4 on 2024-04-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='plot_identifier',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
