# Generated by Django 5.0.2 on 2024-04-23 22:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_plot_plot_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='landscape_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='portrait_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plot',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.person', unique=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_identifier',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plot_status',
            name='color_hex',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Enter a valid hex color code, including the '#' prefix, consisting of 6 digits (0-9, A-F).", regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddConstraint(
            model_name='plot',
            constraint=models.UniqueConstraint(fields=('plot_latitude', 'plot_longitude'), name='unique_plot_location'),
        ),
    ]
