# Generated by Django 5.0.2 on 2024-04-23 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_person_landscape_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='person_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.person'),
        ),
    ]
