# Generated by Django 5.0.2 on 2024-05-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_person_landscape_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='landscape_image',
        ),
        migrations.RemoveField(
            model_name='person',
            name='portrait_image',
        ),
        migrations.AddField(
            model_name='person',
            name='landscape_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='portrait_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
